# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS sbnana::CAFAnaCore sbnana::CAFAnaUnfold sbnana::CAFAnaVars sbnana::CAFAnaCuts sbnana::CAFAnaSysts sbnana::CAFAnaExtrap sbnana::CAFAnaPrediction sbnana::CAFAnaExperiment sbnana::CAFAnaXSec sbnana::CAFAnaAnalysis sbnana::diff_spectra sbnana::concat_cafs sbnana::SBNAnaVars sbnana::SBNAnaCuts sbnana::flatten_caf)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target sbnana::CAFAnaCore
add_library(sbnana::CAFAnaCore SHARED IMPORTED)

set_target_properties(sbnana::CAFAnaCore PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "sbnanaobj::StandardRecordProxy;sbnanaobj::StandardRecord;-L/cvmfs/sbn.opensciencegrid.org/products/sbn/osclib/v00.22/slf7.x86_64.e20.n315.prof.stanfree/lib;OscLib;Threads::Threads;ROOT::Core;ifdh::ifdh;Eigen3::Eigen;Boost::system"
)

# Create imported target sbnana::CAFAnaUnfold
add_library(sbnana::CAFAnaUnfold SHARED IMPORTED)

set_target_properties(sbnana::CAFAnaUnfold PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "sbnana::CAFAnaCore"
)

# Create imported target sbnana::CAFAnaVars
add_library(sbnana::CAFAnaVars SHARED IMPORTED)

set_target_properties(sbnana::CAFAnaVars PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "sbnana::CAFAnaCore;sbnanaobj::StandardRecordProxy;-L/cvmfs/sbn.opensciencegrid.org/products/sbn/osclib/v00.22/slf7.x86_64.e20.n315.prof.stanfree/lib;OscLib"
)

# Create imported target sbnana::CAFAnaCuts
add_library(sbnana::CAFAnaCuts SHARED IMPORTED)

set_target_properties(sbnana::CAFAnaCuts PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "sbnana::CAFAnaCore;sbnanaobj::StandardRecordProxy"
)

# Create imported target sbnana::CAFAnaSysts
add_library(sbnana::CAFAnaSysts SHARED IMPORTED)

set_target_properties(sbnana::CAFAnaSysts PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "sbnana::CAFAnaCore;sbnana::CAFAnaCuts;sbnanaobj::StandardRecordProxy"
)

# Create imported target sbnana::CAFAnaExtrap
add_library(sbnana::CAFAnaExtrap SHARED IMPORTED)

set_target_properties(sbnana::CAFAnaExtrap PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "sbnana::CAFAnaCore;sbnana::CAFAnaCuts"
)

# Create imported target sbnana::CAFAnaPrediction
add_library(sbnana::CAFAnaPrediction SHARED IMPORTED)

set_target_properties(sbnana::CAFAnaPrediction PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "sbnana::CAFAnaCore;sbnana::CAFAnaSysts;sbnana::CAFAnaExtrap"
)

# Create imported target sbnana::CAFAnaExperiment
add_library(sbnana::CAFAnaExperiment SHARED IMPORTED)

set_target_properties(sbnana::CAFAnaExperiment PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "sbnana::CAFAnaCore;sbnana::CAFAnaVars;sbnana::CAFAnaPrediction;-L/cvmfs/sbn.opensciencegrid.org/products/sbn/osclib/v00.22/slf7.x86_64.e20.n315.prof.stanfree/lib;OscLib"
)

# Create imported target sbnana::CAFAnaXSec
add_library(sbnana::CAFAnaXSec SHARED IMPORTED)

set_target_properties(sbnana::CAFAnaXSec PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "sbnana::CAFAnaCore"
)

# Create imported target sbnana::CAFAnaAnalysis
add_library(sbnana::CAFAnaAnalysis SHARED IMPORTED)

set_target_properties(sbnana::CAFAnaAnalysis PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "sbnana::CAFAnaCore;sbnana::CAFAnaExperiment;ROOT::Minuit2"
)

# Create imported target sbnana::diff_spectra
add_executable(sbnana::diff_spectra IMPORTED)

# Create imported target sbnana::concat_cafs
add_executable(sbnana::concat_cafs IMPORTED)

# Create imported target sbnana::SBNAnaVars
add_library(sbnana::SBNAnaVars SHARED IMPORTED)

set_target_properties(sbnana::SBNAnaVars PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "sbnana::CAFAnaCore;sbnanaobj::StandardRecordProxy;-L/cvmfs/sbn.opensciencegrid.org/products/sbn/osclib/v00.22/slf7.x86_64.e20.n315.prof.stanfree/lib;OscLib"
)

# Create imported target sbnana::SBNAnaCuts
add_library(sbnana::SBNAnaCuts SHARED IMPORTED)

set_target_properties(sbnana::SBNAnaCuts PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "sbnana::CAFAnaCore;sbnana::SBNAnaVars;sbnanaobj::StandardRecordProxy"
)

# Create imported target sbnana::flatten_caf
add_executable(sbnana::flatten_caf IMPORTED)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/sbnanaTargets-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
    if(NOT EXISTS "${_cmake_file}")
      message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
